baseURL: "https://ashutoshsingh1093.netlify.app"
languageCode: en-us
title: Ashutosh Singh
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: About
      name: About
      url: /about
      weight: 17
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: experience
      name: Professional Experience
      url: /experience
      weight: 30
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60


params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Ashutosh Singh"
    subtitle: "Data Science Professional with 8 years of experience leveraging data analytics to drive actionable insights and optimize decision-making across **Retail, Marketing, and Insurance industries**. Skilled in **SQL, Python, ETL, statistical analysis, and data visualization**, with a strong background in **customer analytics, marketing optimization, and predictive modeling**. Adept at working with large datasets in platforms like **Azure Databricks, Tableau, and PowerBI** to deliver impactful results. I graduated from **Northeastern University, Boston** with a **Master of Science in Artificial Intelligence**. With **8 years** of Professional experience as a **Senior CRM Data Analyst** at **Sally Beauty**, **Senior Data Analytics Consultant** at **NTT DATA** and **Business Data Analyst** at **Xerox Services**, I bring valuable industry knowledge."
    imageUrl: "home/SAS.jpg"
    imageWidth: 300
    imageHeight: 300 
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/11B4gf0I6SSJZCxVrGe8awj2DaYAKjiBm/view?usp=drive_link"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:singh.ashut@northeastern.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ashutoshkumarsingh1009/"  
    - name: "github"
      url: "https://github.com/Abhiashu10"
    - name: "kaggle"
      url: "https://www.kaggle.com/ashutoshsingh1093"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
